name: 'Real Creative Digital '
favicon: null
layout_spectrum: 0.3583217207342386
typography_spectrum: 0.5268510312307626
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#978475'
    - '#99afbc'
    - '#510f0f'
    - '#295577'
  brandStrength: 0.05106086959131062
  lightness: 0.09151997766457498
  saturation: 0.12088337424211204
  rhythmicContrast: 0.8680727283935994
purpose: []
